configs = {
        "221":  {'maze height'   : 2,
                 'maze width'    : 2,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (3, 22),
                 'maze'          : "mazes/2x2_rooms_7x7_cells_1_profiles_maze.npy",
                 'rooms'         : "mazes/2x2_rooms_7x7_cells_1_profiles_rooms.npy",
                 'states'        : "mazes/2x2_rooms_7x7_cells_1_profiles_states.npy",
                 'sub length'    : 10,
                 'episode length': 100},


        "222":  {'maze height'   : 2,
                 'maze width'    : 2,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (3, 22),
                 'maze'          : "mazes/2x2_rooms_7x7_cells_2_profiles_maze.npy",
                 'rooms'         : "mazes/2x2_rooms_7x7_cells_2_profiles_rooms.npy",
                 'states'        : "mazes/2x2_rooms_7x7_cells_2_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 100},

        "223":  {'maze height'   : 2,
                 'maze width'    : 2,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (3, 22),
                 'maze'          : "mazes/2x2_rooms_7x7_cells_3_profiles_maze.npy",
                 'rooms'         : "mazes/2x2_rooms_7x7_cells_3_profiles_rooms.npy",
                 'states'        : "mazes/2x2_rooms_7x7_cells_3_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 100},


        "224":  {'maze height'   : 2,
                 'maze width'    : 2,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (3, 22),
                 'maze'          : "mazes/2x2_rooms_7x7_cells_4_profiles_maze.npy",
                 'rooms'         : "mazes/2x2_rooms_7x7_cells_4_profiles_rooms.npy",
                 'states'        : "mazes/2x2_rooms_7x7_cells_4_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 100},


        "441":  {'maze height'   : 4,
                 'maze width'    : 4,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (15, 22),
                 'maze'          : "mazes/4x4_rooms_7x7_cells_1_profiles_maze.npy",
                 'rooms'         : "mazes/4x4_rooms_7x7_cells_1_profiles_rooms.npy",
                 'states'        : "mazes/4x4_rooms_7x7_cells_1_profiles_states.npy",
                 'sub length'    : 10,
                 'episode length': 200},

        "442":  {'maze height'   : 4,
                 'maze width'    : 4,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (15, 22),
                 'maze'          : "mazes/4x4_rooms_7x7_cells_2_profiles_maze.npy",
                 'rooms'         : "mazes/4x4_rooms_7x7_cells_2_profiles_rooms.npy",
                 'states'        : "mazes/4x4_rooms_7x7_cells_2_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 200},

        "443":  {'maze height'   : 4,
                 'maze width'    : 4,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (15, 22),
                 'maze'          : "mazes/4x4_rooms_7x7_cells_3_profiles_maze.npy",
                 'rooms'         : "mazes/4x4_rooms_7x7_cells_3_profiles_rooms.npy",
                 'states'        : "mazes/4x4_rooms_7x7_cells_3_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 200},

        "444":  {'maze height'   : 4,
                 'maze width'    : 4,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (15, 22),
                 'maze'          : "mazes/4x4_rooms_7x7_cells_4_profiles_maze.npy",
                 'rooms'         : "mazes/4x4_rooms_7x7_cells_4_profiles_rooms.npy",
                 'states'        : "mazes/4x4_rooms_7x7_cells_4_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 200},


        "881":  {'maze height'   : 8,
                 'maze width'    : 8,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (63, 22),
                 'maze'          : "mazes/8x8_rooms_7x7_cells_1_profiles_maze.npy",
                 'rooms'         : "mazes/8x8_rooms_7x7_cells_1_profiles_rooms.npy",
                 'states'        : "mazes/8x8_rooms_7x7_cells_1_profiles_states.npy",
                 'sub length'    : 10,
                 'episode length': 1000},

        "882":  {'maze height'   : 8,
                 'maze width'    : 8,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (63, 22),
                 'maze'          : "mazes/8x8_rooms_7x7_cells_2_profiles_maze.npy",
                 'rooms'         : "mazes/8x8_rooms_7x7_cells_2_profiles_rooms.npy",
                 'states'        : "mazes/8x8_rooms_7x7_cells_2_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 2000},

        "883":  {'maze height'   : 8,
                 'maze width'    : 8,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (63, 22),
                 'maze'          : "mazes/8x8_rooms_7x7_cells_3_profiles_maze.npy",
                 'rooms'         : "mazes/8x8_rooms_7x7_cells_3_profiles_rooms.npy",
                 'states'        : "mazes/8x8_rooms_7x7_cells_3_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 2000},

        "884":  {'maze height'   : 8,
                 'maze width'    : 8,
                 'room height'   : 7,
                 'room width'    : 7,
                 'goal loc'      : (63, 22),
                 'maze'          : "mazes/8x8_rooms_7x7_cells_4_profiles_maze.npy",
                 'rooms'         : "mazes/8x8_rooms_7x7_cells_4_profiles_rooms.npy",
                 'states'        : "mazes/8x8_rooms_7x7_cells_4_profiles_states.npy",
                 'sub length'    : 20,
                 'episode length': 2000},


        "16161":  {'maze height'   : 16,
                   'maze width'    : 16,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (255, 22),
                   'maze'          : "mazes/16x16_rooms_7x7_cells_1_profiles_maze.npy",
                   'rooms'         : "mazes/16x16_rooms_7x7_cells_1_profiles_rooms.npy",
                   'states'        : "mazes/16x16_rooms_7x7_cells_1_profiles_states.npy",
                   'sub length'    : 10,
                   'episode length': 5000},

        "16162":  {'maze height'   : 16,
                   'maze width'    : 16,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (255, 22),
                   'maze'          : "mazes/16x16_rooms_7x7_cells_2_profiles_maze.npy",
                   'rooms'         : "mazes/16x16_rooms_7x7_cells_2_profiles_rooms.npy",
                   'states'        : "mazes/16x16_rooms_7x7_cells_2_profiles_states.npy",
                   'sub length'    : 20,
                   'episode length': 5000},

        "16163":  {'maze height'   : 16,
                   'maze width'    : 16,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (255, 22),
                   'maze'          : "mazes/16x16_rooms_7x7_cells_3_profiles_maze.npy",
                   'rooms'         : "mazes/16x16_rooms_7x7_cells_3_profiles_rooms.npy",
                   'states'        : "mazes/16x16_rooms_7x7_cells_3_profiles_states.npy",
                   'sub length'    : 20,
                   'episode length': 5000},

        "16164":  {'maze height'   : 16,
                   'maze width'    : 16,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (255, 22),
                   'maze'          : "mazes/16x16_rooms_7x7_cells_4_profiles_maze.npy",
                   'rooms'         : "mazes/16x16_rooms_7x7_cells_4_profiles_rooms.npy",
                   'states'        : "mazes/16x16_rooms_7x7_cells_4_profiles_states.npy",
                   'sub length'    : 20,
                   'episode length': 5000},


        "32321":  {'maze height'   : 32,
                   'maze width'    : 32,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (1023, 22),
                   'maze'          : "mazes/32x32_rooms_7x7_cells_1_profiles_maze.npy",
                   'rooms'         : "mazes/32x32_rooms_7x7_cells_1_profiles_rooms.npy",
                   'states'        : "mazes/32x32_rooms_7x7_cells_1_profiles_states.npy",
                   'sub length'    : 10,
                   'episode length': 10000},

        "32322":  {'maze height'   : 32,
                   'maze width'    : 32,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (1023, 22),
                   'maze'          : "mazes/32x32_rooms_7x7_cells_2_profiles_maze.npy",
                   'rooms'         : "mazes/32x32_rooms_7x7_cells_2_profiles_rooms.npy",
                   'states'        : "mazes/32x32_rooms_7x7_cells_2_profiles_states.npy",
                   'sub length'    : 20,
                   'episode length': 10000},

        "32323":  {'maze height'   : 32,
                   'maze width'    : 32,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (1023, 22),
                   'maze'          : "mazes/32x32_rooms_7x7_cells_3_profiles_maze.npy",
                   'rooms'         : "mazes/32x32_rooms_7x7_cells_3_profiles_rooms.npy",
                   'states'        : "mazes/32x32_rooms_7x7_cells_3_profiles_states.npy",
                   'sub length'    : 20,
                   'episode length': 10000},

        "32324":  {'maze height'   : 32,
                   'maze width'    : 32,
                   'room height'   : 7,
                   'room width'    : 7,
                   'goal loc'      : (1023, 22),
                   'maze'          : "mazes/32x32_rooms_7x7_cells_4_profiles_maze.npy",
                   'rooms'         : "mazes/32x32_rooms_7x7_cells_4_profiles_rooms.npy",
                   'states'        : "mazes/32x32_rooms_7x7_cells_4_profiles_states.npy",
                   'sub length'    : 20,
                   'episode length': 10000}
}


